### PR TITLE
chore: autopopulate readme allowlists

### PR DESCRIPTION
**Pull request by matthewdean-semgrep**
Ensure allowlist URLs in README stay up to date by adding a pre-commit hook which automatically extracts allowlist URLs and places them in the appropriate place in the README. Tool is built independently from main broker code so only contributors to Network Broker will need to build or run it.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -94,38 +94,48 @@ inbound:
...
+- PATCH `https://github.example.com/repos/:org/:repo/check-runs/:check_run_id`
+- PATCH `https://github.example.com/repos/:org/:repo/pulls/:number/comments/:comment_id`
+- DELETE `https://github.example.com/orgs/:org/hooks/:hook_id`
+<!-- EndAutogeneratedAllowList:Github -->
 
 And if `allowCodeAccess` is set, additionally:
 
-- GET `https://github.example.com/api/v3/repos/:org/:repo/contents/*`
-- GET `https://github.example.com/api/v3/repos/:org/:repo/commits`
+<!-- BeginAutogeneratedAllowList:Github.AllowCodeAccess -->
```
Comment (armchairlinguist) [inline README.md:137]: Presumably this shouldn't be empty?

Comment (matthewdean-semgrep) [reply README.md:137]: Correct, thanks for spotting this. When I refactored some code to use reflection, I missed the fact that service providers capitalization varies between what is defined in these `README.md` autogenerated code tags vs the field in `config.Inbound.<ServiceProviderName>`. Fixed by switching from reflection back to a case statement, which will cause compilation errors if we are using the wrong capitalization.

**Review by vivekkhimani — APPROVED** [review]
This looks good to me! Thank you for making it independent from the network broker. By doing so, it becomes a two-way door, allowing us to easily modify or deprecate it if something breaks.
